//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.06 at 10:40:53 PM CST 
//


package com.ylink.upp.oxm.entity.upp_801_001_01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "grpBody", propOrder = {
		"payTranSn",
		"merSeqId",
		"refundAmt",
		"merRefundSn",
		"sonMerNo",
		"refundDate",
		"notifyUrl",
		"returnUrl",
		"resv"
})
public class GrpBody {

    @XmlElement(name = "PayTranSn", required = true)
    protected String payTranSn;
    @XmlElement(name = "MerSeqId")
    protected String merSeqId;
    @XmlElement(name = "RefundAmt", required = true)
    protected String refundAmt;
    @XmlElement(name = "MerRefundSn", required = true)
    protected String merRefundSn;
    @XmlElement(name = "SonMerNo", required = true)
    protected String sonMerNo;
    @XmlElement(name = "RefundDate", required = true)
    protected String refundDate;
    @XmlElement(name = "NotifyUrl", required = true)
    protected String notifyUrl;
    @XmlElement(name = "ReturnUrl", required = true)
    protected String returnUrl;
    @XmlElement(name = "Resv")
    protected String resv;
	public String getPayTranSn() {
		return payTranSn;
	}
	public void setPayTranSn(String payTranSn) {
		this.payTranSn = payTranSn;
	}
	public String getMerSeqId() {
		return merSeqId;
	}
	public void setMerSeqId(String merSeqId) {
		this.merSeqId = merSeqId;
	}
	public String getRefundAmt() {
		return refundAmt;
	}
	public void setRefundAmt(String refundAmt) {
		this.refundAmt = refundAmt;
	}
	public String getMerRefundSn() {
		return merRefundSn;
	}
	public void setMerRefundSn(String merRefundSn) {
		this.merRefundSn = merRefundSn;
	}
	public String getSonMerNo() {
		return sonMerNo;
	}
	public void setSonMerNo(String sonMerNo) {
		this.sonMerNo = sonMerNo;
	}
	public String getRefundDate() {
		return refundDate;
	}
	public void setRefundDate(String refundDate) {
		this.refundDate = refundDate;
	}
	public String getNotifyUrl() {
		return notifyUrl;
	}
	public void setNotifyUrl(String notifyUrl) {
		this.notifyUrl = notifyUrl;
	}
	public String getReturnUrl() {
		return returnUrl;
	}
	public void setReturnUrl(String returnUrl) {
		this.returnUrl = returnUrl;
	}
	public String getResv() {
		return resv;
	}
	public void setResv(String resv) {
		this.resv = resv;
	}

}
