//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.06 at 10:40:53 PM CST 
//


package com.ylink.upp.oxm.entity.upp_801_001_01;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ylink.upp.oxm.entity.upp_103_001_01 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ylink.upp.oxm.entity.upp_103_001_01
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RespInfo }
     * 
     */
    public RespInfo createRespInfo() {
        return new RespInfo();
    }

    /**
     * Create an instance of {@link GrpHdr }
     * 
     */
    public GrpHdr createGrpHdr() {
        return new GrpHdr();
    }

    /**
     * Create an instance of {@link GrpBody }
     * 
     */
    public GrpBody createGrpBody() {
        return new GrpBody();
    }

}
