//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 07:13:16 PM CST 
//


package com.ylink.upp.oxm.entity.upp_510_001_01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for grpBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="grpBody">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OperateType" type="{510.001.01}Max2Text"/>
 *         &lt;element name="OpenCustNo" type="{510.001.01}ExactMax50Text"/>
 *         &lt;element name="CustNo" type="{510.001.01}Max64Text" minOccurs="0"/>
 *         &lt;element name="CustBase" type="{510.001.01}custBase"/>
 *         &lt;element name="Resv" type="{510.001.01}Max120Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "grpBody", propOrder = {
    "operateType",
    "openCustNo",
    "custNo",
    "custBase",
    "resv"
})
public class GrpBody {

    @XmlElement(name = "OperateType", required = true)
    protected String operateType;
    @XmlElement(name = "OpenCustNo", required = true)
    protected String openCustNo;
    @XmlElement(name = "CustNo")
    protected String custNo;
    @XmlElement(name = "CustBase", required = true)
    protected CustBase custBase;
    @XmlElement(name = "Resv")
    protected String resv;

    /**
     * Gets the value of the operateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * Sets the value of the operateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperateType(String value) {
        this.operateType = value;
    }

    /**
     * Gets the value of the openCustNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenCustNo() {
        return openCustNo;
    }

    /**
     * Sets the value of the openCustNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenCustNo(String value) {
        this.openCustNo = value;
    }

    /**
     * Gets the value of the custNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * Sets the value of the custNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustNo(String value) {
        this.custNo = value;
    }

    /**
     * Gets the value of the custBase property.
     * 
     * @return
     *     possible object is
     *     {@link CustBase }
     *     
     */
    public CustBase getCustBase() {
        return custBase;
    }

    /**
     * Sets the value of the custBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustBase }
     *     
     */
    public void setCustBase(CustBase value) {
        this.custBase = value;
    }

    /**
     * Gets the value of the resv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResv() {
        return resv;
    }

    /**
     * Sets the value of the resv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResv(String value) {
        this.resv = value;
    }

}
