//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.26 at 04:06:30 PM CST 
//


package com.ylink.upp.oxm.entity.upp_301_001_01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PayOrderDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayOrderDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MerSeqId" type="{301.001.01}Max50Text"/>
 *         &lt;element name="MerName" type="{301.001.01}Max50Text" minOccurs="0"/>
 *         &lt;element name="ProductName" type="{301.001.01}Max64Text"/>
 *         &lt;element name="ProductAmt" type="{301.001.01}ExactMax18NumberText"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayOrderDetail", propOrder = {
    "merSeqId",
    "merName",
    "productName",
    "productAmt"
})
public class PayOrderDetail {

    @XmlElement(name = "MerSeqId", required = true)
    protected String merSeqId;
    @XmlElement(name = "MerName")
    protected String merName;
    @XmlElement(name = "ProductName", required = true)
    protected String productName;
    @XmlElement(name = "ProductAmt", required = true)
    protected String productAmt;

    /**
     * Gets the value of the merSeqId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerSeqId() {
        return merSeqId;
    }

    /**
     * Sets the value of the merSeqId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerSeqId(String value) {
        this.merSeqId = value;
    }

    /**
     * Gets the value of the merName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerName() {
        return merName;
    }

    /**
     * Sets the value of the merName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerName(String value) {
        this.merName = value;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the productAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductAmt() {
        return productAmt;
    }

    /**
     * Sets the value of the productAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductAmt(String value) {
        this.productAmt = value;
    }

}
