//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.26 at 04:06:30 PM CST 
//


package com.ylink.upp.oxm.entity.upp_301_001_01;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stsRsnInf complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stsRsnInf">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PayTranSn" type="{301.001.01}Max50Text"/>
 *         &lt;element name="MerOrderId" type="{301.001.01}Max50Text"/>
 *         &lt;element name="OrderStatus" type="{301.001.01}Max2Text"/>
 *         &lt;element name="OrderAmt" type="{301.001.01}ExactMax18NumberText"/>
 *         &lt;element name="CloseTime" type="{301.001.01}Exact14Text" minOccurs="0"/>
 *         &lt;element name="PaymentChannel" type="{301.001.01}Max2Text" minOccurs="0"/>
 *         &lt;element name="PaymentMethod" type="{301.001.01}Max2Text" minOccurs="0"/>
 *         &lt;element name="PayOrderDetail" type="{301.001.01}PayOrderDetail" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stsRsnInf", propOrder = {
    "payTranSn",
    "merOrderId",
    "orderStatus",
    "orderAmt",
    "closeTime",
    "paymentChannel",
    "paymentMethod",
    "payOrderDetail"
})
public class StsRsnInf {

    @XmlElement(name = "PayTranSn", required = true)
    protected String payTranSn;
    @XmlElement(name = "MerOrderId", required = true)
    protected String merOrderId;
    @XmlElement(name = "OrderStatus", required = true)
    protected String orderStatus;
    @XmlElement(name = "OrderAmt", required = true)
    protected String orderAmt;
    @XmlElement(name = "CloseTime")
    protected String closeTime;
    @XmlElement(name = "PaymentChannel")
    protected String paymentChannel;
    @XmlElement(name = "PaymentMethod")
    protected String paymentMethod;
    @XmlElement(name = "PayOrderDetail")
    protected List<PayOrderDetail> payOrderDetail;

    /**
     * Gets the value of the payTranSn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayTranSn() {
        return payTranSn;
    }

    /**
     * Sets the value of the payTranSn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayTranSn(String value) {
        this.payTranSn = value;
    }

    /**
     * Gets the value of the merOrderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerOrderId() {
        return merOrderId;
    }

    /**
     * Sets the value of the merOrderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerOrderId(String value) {
        this.merOrderId = value;
    }

    /**
     * Gets the value of the orderStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * Sets the value of the orderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderStatus(String value) {
        this.orderStatus = value;
    }

    /**
     * Gets the value of the orderAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderAmt() {
        return orderAmt;
    }

    /**
     * Sets the value of the orderAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderAmt(String value) {
        this.orderAmt = value;
    }

    /**
     * Gets the value of the closeTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloseTime() {
        return closeTime;
    }

    /**
     * Sets the value of the closeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloseTime(String value) {
        this.closeTime = value;
    }

    /**
     * Gets the value of the paymentChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentChannel() {
        return paymentChannel;
    }

    /**
     * Sets the value of the paymentChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentChannel(String value) {
        this.paymentChannel = value;
    }

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentMethod(String value) {
        this.paymentMethod = value;
    }

    /**
     * Gets the value of the payOrderDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payOrderDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayOrderDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PayOrderDetail }
     * 
     * 
     */
    public List<PayOrderDetail> getPayOrderDetail() {
        if (payOrderDetail == null) {
            payOrderDetail = new ArrayList<PayOrderDetail>();
        }
        return this.payOrderDetail;
    }

	public void setPayOrderDetail(List<PayOrderDetail> payOrderDetail) {
		this.payOrderDetail = payOrderDetail;
	}
    
}
