//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.09 at 10:25:38 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "upp.600.001.01", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ylink.upp.oxm.entity.upp_600_001_01;
