//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.13 at 02:56:33 PM CST 
//


package com.ylink.upp.oxm.entity.upp_300_001_01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for grpBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="grpBody">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PayTranSn" type="{300.001.01}Max50Text" minOccurs="0"/>
 *         &lt;element name="MerOrderId" type="{300.001.01}Max50Text" minOccurs="0"/>
 *         &lt;element name="Resv" type="{300.001.01}Max128Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "grpBody", propOrder = {
    "payTranSn",
    "merOrderId",
    "resv"
})
public class GrpBody {

    @XmlElement(name = "PayTranSn")
    protected String payTranSn;
    @XmlElement(name = "MerOrderId")
    protected String merOrderId;
    @XmlElement(name = "Resv")
    protected String resv;

    /**
     * Gets the value of the payTranSn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayTranSn() {
        return payTranSn;
    }

    /**
     * Sets the value of the payTranSn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayTranSn(String value) {
        this.payTranSn = value;
    }

    /**
     * Gets the value of the merOrderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerOrderId() {
        return merOrderId;
    }

    /**
     * Sets the value of the merOrderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerOrderId(String value) {
        this.merOrderId = value;
    }

    /**
     * Gets the value of the resv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResv() {
        return resv;
    }

    /**
     * Sets the value of the resv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResv(String value) {
        this.resv = value;
    }

}
