//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.06 at 10:40:53 PM CST 
//

package com.ylink.upp.oxm.entity.upp_803_001_01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "grpBody", propOrder = { "refundSn", "merRefundSn", "refundAmt", "refundStatus", "refundDate", "resv" })
public class GrpBody {

	@XmlElement(name = "refundSn", required = true)
	protected String refundSn;
	@XmlElement(name = "merRefundSn")
	protected String merRefundSn;
	@XmlElement(name = "refundAmt", required = true)
	protected long refundAmt;
	@XmlElement(name = "refundStatus", required = true)
	protected String refundStatus;
	@XmlElement(name = "refundDate", required = true)
	protected long refundDate;
	@XmlElement(name = "Resv")
	protected String resv;

	public String getRefundSn() {
		return refundSn;
	}

	public void setRefundSn(String refundSn) {
		this.refundSn = refundSn;
	}

	public String getMerRefundSn() {
		return merRefundSn;
	}

	public void setMerRefundSn(String merRefundSn) {
		this.merRefundSn = merRefundSn;
	}

	public long getRefundAmt() {
		return refundAmt;
	}

	public void setRefundAmt(long refundAmt) {
		this.refundAmt = refundAmt;
	}

	public String getRefundStatus() {
		return refundStatus;
	}

	public void setRefundStatus(String refundStatus) {
		this.refundStatus = refundStatus;
	}

	public long getRefundDate() {
		return refundDate;
	}

	public void setRefundDate(long refundDate) {
		this.refundDate = refundDate;
	}

	public String getResv() {
		return resv;
	}

	public void setResv(String resv) {
		this.resv = resv;
	}

}
